# Generated by Django 2.2.4 on 2019-08-18 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tech_title', models.CharField(max_length=255, verbose_name='Техническое название')),
                ('visible', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, null=True)),
                ('visible', models.BooleanField()),
                ('related_with', models.CharField(choices=[('video', 'video_courses'), ('event', 'events')], max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.Menu', verbose_name='id Menu')),
                ('menu_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.Menu_item', verbose_name='id Menu item')),
            ],
            options={
                'verbose_name': 'Пункт Меню',
                'verbose_name_plural': 'Пункты Меню',
            },
        ),
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('iamges', models.ImageField(blank=True, upload_to='images/')),
                ('block_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.Blocks', verbose_name='id Block')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
    ]
