# Generated by Django 2.2.4 on 2019-08-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0002_auto_20190818_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seo_title', models.CharField(max_length=255)),
                ('seo_description', models.CharField(max_length=255)),
                ('seo_keywords', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
