# Generated by Django 2.2.4 on 2019-08-19 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0003_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='page_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.Page', verbose_name='related Page'),
        ),
    ]
