# Generated by Django 2.2.4 on 2019-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0004_blocks_page_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
