# Generated by Django 2.2.4 on 2019-08-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0005_auto_20190819_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='tech_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Техническое название'),
        ),
    ]
