# Generated by Django 2.2.4 on 2019-08-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0006_page_tech_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='sclug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
