# Generated by Django 2.2.4 on 2019-08-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0008_auto_20190828_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
            },
        ),
        migrations.RenameField(
            model_name='blocks',
            old_name='iamges',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='sclug',
            new_name='slug',
        ),
    ]
