# Generated by Django 2.2.4 on 2019-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0009_auto_20190828_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Видеокурс',
                'verbose_name_plural': 'Видеокурсы',
            },
        ),
        migrations.AlterModelOptions(
            name='videocourses',
            options={'verbose_name': 'Видеокурс', 'verbose_name_plural': 'Видеокурсы'},
        ),
        migrations.AddField(
            model_name='blocks',
            name='texh_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Техническое имя'),
        ),
    ]
