# Generated by Django 2.2.4 on 2019-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0012_auto_20190829_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
