# Generated by Django 2.2.4 on 2019-09-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0013_events_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='prior',
            field=models.IntegerField(default=100, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blocks',
            name='tech_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Техническое имя'),
        ),
    ]
