# Generated by Django 2.2.4 on 2019-09-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0015_callback_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Уроки',
            },
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='text',
            field=models.TextField(blank=True, choices=[('1-11', '1-11 недель'), ('12-19', '12-19 недель'), ('20-29', '20-29 недель'), ('30-41', '30-41 недель'), ('После родов', 'После родов')], verbose_name='Неделя беременности'),
        ),
    ]
