# Generated by Django 2.2.4 on 2019-09-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0016_auto_20190910_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourses',
            name='lesson_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.Lessons', verbose_name='Уроки курса'),
        ),
    ]
