# Generated by Django 2.2.4 on 2019-09-10 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0017_videocourses_lesson_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocourses',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='lessons',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.VideoCourses', verbose_name='Видеокурс'),
        ),
    ]
