# Generated by Django 2.2.4 on 2019-09-10 16:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0019_coursesvariants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='coursesvariants',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='events',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='videocourses',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Text'),
        ),
    ]
