# Generated by Django 2.2.4 on 2019-09-11 10:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0020_auto_20190910_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
