# Generated by Django 2.2.4 on 2019-09-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0021_auto_20190911_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourses',
            name='on_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='Выводить на главной'),
        ),
        migrations.AddField(
            model_name='videocourses',
            name='prior',
            field=models.IntegerField(default=100, verbose_name='Приоритет'),
        ),
    ]
