# Generated by Django 2.2.4 on 2019-09-11 12:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0022_auto_20190911_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourses',
            name='about_course',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='videocourses',
            name='students_results',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
