# Generated by Django 2.2.4 on 2019-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0024_auto_20190911_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='amount',
            field=models.IntegerField(default=100, verbose_name='Приоритет'),
        ),
    ]
