# Generated by Django 2.2.4 on 2019-09-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0025_subscribe_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='amount',
            field=models.IntegerField(default=100, verbose_name='Неделя беременности'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='personal_agree',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.CreateModel(
            name='MenuItemBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=500, verbose_name='Приоритет')),
                ('link_url', models.CharField(help_text='URL or URI to the content, eg /about/ or http://foo.com/', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('display_video', models.BooleanField(blank=True, default=False)),
                ('display_event', models.BooleanField(blank=True, default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.MenuBlocks', verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
