# Generated by Django 2.2.4 on 2019-09-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0026_auto_20190911_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menublocks',
            name='slug',
            field=models.TextField(),
        ),
    ]
