# Generated by Django 2.2.4 on 2019-09-11 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0028_menuitemblocks_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemblocks',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.MenuBlocks', verbose_name='Имя'),
        ),
    ]
