# Generated by Django 2.2.4 on 2019-09-11 18:52

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0029_auto_20190911_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Text')),
                ('autor', models.CharField(max_length=255, verbose_name='Автор')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.VideoCourses', verbose_name='Видеокурс')),
            ],
            options={
                'verbose_name': 'Варианты курса',
            },
        ),
    ]
