# Generated by Django 2.2.4 on 2019-09-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0030_coursesreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesreviews',
            options={'verbose_name': 'Отзывы о курсе'},
        ),
        migrations.AddField(
            model_name='coursesvariants',
            name='price_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сыылка на оплату'),
        ),
    ]
