# Generated by Django 2.2.4 on 2019-09-12 15:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0032_auto_20190912_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocourses',
            name='second_text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Second_text'),
        ),
    ]
