# Generated by Django 2.2.4 on 2019-09-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0033_videocourses_second_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocks',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка в блоке(youtube, insta, or other)'),
        ),
    ]
