# Generated by Django 2.2.4 on 2019-09-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0035_auto_20190913_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
