# Generated by Django 2.2.4 on 2019-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0038_auto_20190913_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(default='empty@emty.ru', max_length=255, unique=True),
        ),
    ]
