# Generated by Django 2.2.4 on 2019-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0042_eventsprogrammitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsprogrammitem',
            options={'verbose_name': 'Части Семинара'},
        ),
        migrations.AlterModelOptions(
            name='eventsvariants',
            options={'verbose_name': 'Варианты Семинара'},
        ),
        migrations.AddField(
            model_name='events',
            name='prior',
            field=models.IntegerField(default=100, verbose_name='Приоритет'),
        ),
    ]
