# Generated by Django 2.2.4 on 2019-09-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0043_auto_20190927_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='events',
            name='video',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
