# Generated by Django 2.2.4 on 2019-09-30 15:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0044_auto_20190927_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Text')),
                ('autor', models.CharField(max_length=255, verbose_name='Автор')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('video', models.CharField(max_length=255, verbose_name='Ссылка на видео')),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.Events', verbose_name='Семинар')),
            ],
            options={
                'verbose_name': 'Отзывы о семинаре',
            },
        ),
    ]
