# Generated by Django 2.2.4 on 2019-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0045_eventsreviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesreviews',
            options={'verbose_name': 'Отзыв о курсе', 'verbose_name_plural': 'Отзывы о курсе'},
        ),
        migrations.AlterModelOptions(
            name='coursesvariants',
            options={'verbose_name': 'Вариант курса', 'verbose_name_plural': 'Варианты курса'},
        ),
        migrations.AlterModelOptions(
            name='eventsprogrammitem',
            options={'verbose_name': 'Часть Семинара', 'verbose_name_plural': 'Части Семинара'},
        ),
        migrations.AlterModelOptions(
            name='eventsreviews',
            options={'verbose_name': 'Отзыв о семинаре', 'verbose_name_plural': 'Отзывы о семинаре'},
        ),
        migrations.AlterModelOptions(
            name='eventsvariants',
            options={'verbose_name': 'Вариант Семинара', 'verbose_name_plural': 'Варианты Семинара'},
        ),
        migrations.AlterModelOptions(
            name='lessons',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterField(
            model_name='coursesvariants',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='videocourses',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
