# Generated by Django 2.2.4 on 2019-10-16 13:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0046_auto_20191007_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='duration',
        ),
        migrations.AlterField(
            model_name='videocourses',
            name='about_course',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='О курсе'),
        ),
        migrations.AlterField(
            model_name='videocourses',
            name='second_text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Дополнительный текст'),
        ),
        migrations.AlterField(
            model_name='videocourses',
            name='students_results',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Результаты студентов'),
        ),
        migrations.AlterField(
            model_name='videocourses',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст'),
        ),
    ]
