# Generated by Django 2.2.4 on 2019-10-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0048_auto_20191016_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocourses',
            name='lesson_text',
        ),
        migrations.AddField(
            model_name='videocourses',
            name='duration_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кол-во часов'),
        ),
        migrations.AddField(
            model_name='videocourses',
            name='lessons_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кол-во уроков'),
        ),
    ]
