# Generated by Django 2.2.4 on 2019-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0049_auto_20191017_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesreviews',
            name='autor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='coursesreviews',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
    ]
