# Generated by Django 2.2.4 on 2019-10-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0050_auto_20191018_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesvariants',
            name='price_link',
            field=models.TextField(blank=True, null=True, verbose_name='Сыылка на оплату'),
        ),
    ]
