# Generated by Django 2.2.4 on 2019-10-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0051_auto_20191018_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterField(
            model_name='callback',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='callback',
            name='personal_agree',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='callback',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='coursesvariants',
            name='price',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='coursesvariants',
            name='price_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventsprogrammitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventsreviews',
            name='autor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='eventsreviews',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='eventsreviews',
            name='video',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='eventsvariants',
            name='price',
            field=models.CharField(blank=True, max_length=255, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='eventsvariants',
            name='price_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='eventsvariants',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
