# Generated by Django 2.2.4 on 2019-10-21 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0052_auto_20191018_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_main', models.BooleanField(blank=True, default=False, verbose_name='Выводить на главной')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('course_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.Events', verbose_name='Семинар')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Места проведения',
            },
        ),
    ]
