# Generated by Django 2.2.4 on 2019-10-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0053_eventsplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsplaces',
            name='visible',
            field=models.BooleanField(blank=True, default=False, verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='eventsplaces',
            name='on_main',
            field=models.BooleanField(blank=True, default=False, verbose_name='Выводить на главной в кружочке'),
        ),
    ]
