# Generated by Django 2.2.4 on 2019-10-24 14:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0054_auto_20191021_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страницы', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.CreateModel(
            name='VideoBlocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Техническое имя')),
                ('prior', models.IntegerField(default=100, verbose_name='Приоритет')),
                ('name', models.CharField(max_length=255)),
                ('text', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Text')),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка в блоке(youtube, insta, or other)')),
                ('block_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.VideoBlocks', verbose_name='id Block')),
                ('page_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.Page', verbose_name='related Page')),
            ],
            options={
                'verbose_name': 'Блок Видеокурса',
                'verbose_name_plural': 'Блоки Видеокурсов',
            },
        ),
    ]
