# Generated by Django 2.2.4 on 2019-10-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0055_auto_20191024_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoblocks',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='videoblocks',
            name='page_id',
        ),
        migrations.AddField(
            model_name='videoblocks',
            name='videocourse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aistsiteapp.VideoCourses', verbose_name='id Видеокурса'),
        ),
        migrations.AlterField(
            model_name='videoblocks',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка в блоке'),
        ),
    ]
