# Generated by Django 2.2.4 on 2019-10-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0056_auto_20191024_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
