# Generated by Django 2.2.4 on 2019-10-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0057_auto_20191025_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
