# Generated by Django 2.2.4 on 2019-10-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aistsiteapp', '0059_auto_20191028_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
