# Generated by Django 2.2.4 on 2019-08-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_booleandefaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='anonymous_only',
            field=models.BooleanField(blank=True, default=False, help_text='Should this item only be shown to non-logged-in users?', verbose_name='Anonymous only'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='login_required',
            field=models.BooleanField(blank=True, default=False, help_text='Should this item only be shown to authenticated users?', verbose_name='Login required'),
        ),
    ]
