# Generated by Django 2.2.4 on 2019-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190828_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='display_event',
            field=models.BooleanField(blank=True, null=True, verbose_name='Event course inside'),
        ),
        migrations.AddField(
            model_name='menu',
            name='display_video',
            field=models.BooleanField(blank=True, null=True, verbose_name='Video course inside'),
        ),
    ]
