# Generated by Django 2.2.4 on 2019-09-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190911_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='display_event',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='display_video',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_event',
            field=models.BooleanField(blank=True, default=False, verbose_name='Event course inside'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_video',
            field=models.BooleanField(blank=True, default=False, verbose_name='Video course inside'),
        ),
    ]
